# This docker compose is for local development purposes

version: "3.7"
services:
  api:
    build: .
    ports:
      - "8080:8080"
  database:
    container_name: database
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'inditex'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'inditex'
